apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: kind-prometheus # must match your Prometheus release
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http              # must match the name in Service
      path: /actuator/prometheus # Spring Boot metrics endpoint
      interval: 15s
  namespaceSelector:
    matchNames:
      - default # namespace where your backend app is running
