apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    release: kind-prometheus # important if using kube-prometheus-stack
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http  
      protocol: TCP
      port: 8081
      targetPort: 8081
